### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'data/results/KBP/rm/prediction_emb_retype_cosine.txt'

### ISSUE THREAD

**Issue by leolle** [shanzhenren/DS-RelationExtraction#14]
when run the script run.sh, I have below error:
```
Learn CoType embeddings...
code/Model/retype/retype: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
...
IOError: [Errno 2] No such file or directory: 'data/results/KBP/rm/prediction_emb_retype_cosine.txt'

```
please tell me how to build libgsl? I already ran the make command under retype folder.

**Comment by ellenmellon** [comment]
Hi, you may wanna take a look at this post: https://stackoverflow.com/questions/22222666/error-while-loading-shared-libraries-libgsl-so-0-cannot-open-shared-object-fil

You could simply do 
```
$ LD_LIBRARY_PATH= path to your gsl lib folder inside the gsl installation folder
$ export LD_LIBRARY_PATH
```
to solve the issue I believe.
